### ISSUE TITLE
Incorrect file linked in README.md

### ISSUE THREAD

**Issue by spicyjack** [bleroy/3d-junkyard#13]
Hi,

In the section of the `README.md` called "Key Caps", there's this paragraph:

> The first solution is to `[3D-print your own](https://github.com/bleroy/3d-junkyard/blob/main/Atari130MX/Caps/fn-choc.stl) `and then paint them. I recommend [Tamiya Sea Grey model paint](https://www.tamiyausa.com/shop/acrylic-paint-flat-mini-10ml/acrylic-mini-xf-83-m-sea-gray/) for a pretty good match with the Atari XE case color. You can mask the legends when painting to make them stand out.

The file `fn-choc.stl` doesn't exist in the repo, so the above Markdown link 404's; is `Atari130MX/Caps/fn-console-set-choc.stl` the correct filename now?

**Comment by bleroy** [comment]
Thanks for the report, I fixed the readme to point at the correct file for console keys.
