### ISSUE TITLE
DecentXE Plate issues

### ISSUE THREAD

**Issue by ProfsRetroFix** [bleroy/3d-junkyard#14]
I've asked PCBWay to make an aluminium plate using the plate gerbers here.

However they've come back to me with a few issues as below:

> Pls check pic#1, 
> 1) In file no drill layer, so the board without drill holes?
> 2) One layer board has 2 soldermask layers, so need produce with both soldermask layers?
> 

Any ideas as to the answers? I'm relatively oblivious to Gerber files I'm afraid. I've attached the image they want me to 'check'.
![1 ](https://github.com/user-attachments/assets/d9020de7-82cf-4299-924e-d7cc2e12b7d6)

**Comment by bleroy** [comment]
I have no idea why PCBWay can't find the inner edge cuts. They are on the same edge cut layer as the outline of the PCB. I've had dozens of this plate made at JLCPCB without issue. JLCPCB is also generally much less expensive.

The board is single layer. They can obviously ignore the second one.
