### ISSUE TITLE
1200XL console keys

### ISSUE THREAD

**Issue by jma7x** [bleroy/3d-junkyard#16]
I'm starting to build a 1200xl keyboard (version 4m), and have a question about the console keys.
The readme says to use Kailh Choc v1 keyswitches, and that matches the 3d model for the caps.  However, the footprint on the pcb seems to be for cherry mx switches only?  Is there a 3d model for caps that will work with those?

Thanks

**Comment by bleroy** [comment]
Oh wow, this is embarrassing, and you're totally right. I have a whole batch of those that I can just throw into the bin. I'll update the design as soon as I can.

**Comment by bleroy** [comment]
Version 5m is in, with the correct footprint. Please use this.
